### ISSUE TITLE
Proot can't sanitize binding 

### ISSUE THREAD

**Issue by Localsvds** [AndronixApp/andronix-docs-next#13]
Hi so I'm trying to run kali linux but I'm always getting an error saying proot: can't sanitize binding. 
Please help me out with this

![IMG_20210914_073246.jpg](https://user-images.githubusercontent.com/72863427/133182803-beb64363-8ca5-4e9d-8ea9-1a61975fee44.jpg)

**Comment by papis801** [comment]
Ooop![IMG_20221204_163636_1.jpg](https://user-images.githubusercontent.com/90222936/205515695-cb1ad1eb-d0ec-4aa2-ac5f-44eb3cc78b8e.jpg)[]()
